name: Test SWIG wrappers

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  swig-python:
    name: Python SWIG wrapper (${{ matrix.go-version }})
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y swig python3-dev

      - name: Build libcoraza
        run: |
          ./build.sh
          ./configure
          make V=1

      - name: Generate and compile Python SWIG wrapper
        run: |
          make -C examples/python

      - name: Run Python example
        run: |
          make -C examples/python run

  swig-java:
    name: Java SWIG wrapper (${{ matrix.go-version }})
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y swig default-jdk

      - name: Build libcoraza
        run: |
          ./build.sh
          ./configure
          make V=1

      - name: Generate and compile Java SWIG wrapper
        run: |
          make -C examples/java

      - name: Run Java example
        run: |
          make -C examples/java run
